basePath: /
definitions:
  models.Node:
    properties:
      id:
        type: integer
      label:
        type: string
      properties:
        $ref: '#/definitions/models.Properties'
    type: object
  models.Properties:
    additionalProperties: {}
    type: object
info:
  contact: {}
  description: EdgeDB API server
  title: EdgeDB API
  version: "1.0"
paths:
  /api/v1/nodes:
    get:
      description: Search and return nodes.
      parameters:
      - default: '""'
        description: search term
        in: query
        name: term
        type: string
      - default: 1000
        description: limit results returned
        in: query
        maximum: 1000
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of nodes
          schema:
            items:
              $ref: '#/definitions/models.Node'
            type: array
        "400":
          description: Bad request
        "500":
          description: Internal server error
      summary: Search and return nodes
      tags:
      - nodes
swagger: "2.0"
